GET /chats/getAll HTTP/1.1
Host: localhost:3300
Content-Type: application/json
LOGIN: eyJhbGciOiJIUzI1NiJ9.YzZhM2ZhMTctNmQ3NS00NGNjLWI1NDYtY2ZkZjIwNDRlMDhl.EHy9pTn61VdWAQPa2SzaUyOdGAy-VnpfATpAnFFAuRA

{
  "name": "Carlos Eduardo",
  "password": "sesos"
}